services:
  nginx:
    image: "${PROJECT_NAME}/nginx:development"
    container_name: ${PROJECT_NAME}-nginx
    build: 
      context: ./
      dockerfile: ./containers/nginx/Dockerfile
    depends_on:
      - php
    tty: true
    ports:
      - 80:80
    volumes:
      - ./artifacts/nginx/:/var/log/nginx:cached
      - ${APP_PATH}:/app:cached
  php:
    image: "${PROJECT_NAME}/php:development"
    container_name: ${PROJECT_NAME}-php
    build:
      context: ./
      dockerfile: ./containers/php/Dockerfile
      target: development
    volumes:
      - ${APP_PATH}:/app:cached
    environment:
      PROJECT_NAME: ${PROJECT_NAME}
  postgres:
    image: "${PROJECT_NAME}/postgres:development"
    container_name: ${PROJECT_NAME}-postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    build:
      context: ./
      dockerfile: ./containers/postgres/Dockerfile
    ports:
      - ${DB_PORT}:5432
    volumes:
      - b5f49a27bb28a7800df0a8ac0490b2d_postgres:/var/lib/postgresql/data

volumes:
  b5f49a27bb28a7800df0a8ac0490b2d_postgres:
